mozilla/metric-hub

- .circleci/config.yml
- definitions/fenix.toml
- definitions/firefox_ios.toml
- definitions/focus_android.toml
- definitions/focus_ios.toml
- definitions/klar_android.toml
- definitions/klar_ios.toml
Adds some of the default metric definitions needed for https://github.com/mozilla/opmon-config
> Add default metrics

- jetstream/README.md
- opmon/README.md
My plan is to:
1. create these folders that will contain the tool configs
2. update jetstream to merge configs from these folders and the existing jetstream-config repo
3. announce that we are changing the location of the configs
4. update docs
5. move jetstream-config into this repo
6. update jetstream to only use configs from this repo
> Add placeholder folder for tooling-specific configs

- definitions/firefox_desktop.toml
After this PR is merged, we will be able to use these Segments with mozanalysis like:
```
from mozanalysis.config import ConfigLoader
pocket_countries = ConfigLoader.get_segment("pocket_countries", app_name="firefox_desktop")
```
> Add country segments

- .github/pull_request_template.md
- .github/workflows/auto-approve.yml
⚠️ A review is required when adding new metric definitions
Reviews are optional for making changes to configs in `jetstream/` or `opmon/`.
> Auto approvals

- jetstream/mr2022-backgroundtaskmessage-notification-release-1pct.toml
- jetstream/mr2022-backgroundtaskmessage-notification-release-2pct-with-holdback.toml
These experiments are at
https://experimenter.services.mozilla.com/nimbus/mr2022-backgroundtaskmessage-notification-release-1pct and
https://experimenter.services.mozilla.com/nimbus/mr2022-backgroundtaskmessage-notification-release-2pct-with-holdback and pose some novel challenges for Jetstream; see the extensive inline commenting.
The second anaylsis is a duplicate of the first analysis, with:
- appropriate dates
- the interpolated experiment slug updated in 2 places.
> Analyis for Firefox update notification experiments.

- definitions/fenix.toml
- definitions/firefox_ios.toml
This PR adds the definitions for the [Mobile Activation Metric](https://docs.google.com/document/d/1ab2bRcmOdkxgLu-Xin7fZ25qFZGY5IyyMEkVCB1jSoQ/edit#), for future use in experiments.
> New profile activation definitions for Fenix and iOS

- .circleci/validation-config.yml
- jetstream/outcomes/firefox_ios/default_browser.toml
- jetstream/rally-first-prompt-for-users-without-an-enrolled-study-2nd-stage-rollout.toml
- jetstream/rally-first-prompt-for-users-without-an-enrolled-study.toml
Depends on https://github.com/mozilla/jetstream/pull/1560
The reason to change this is to only rerun configs that got changed in the PR. Previously, we reran all experiments that had a changed config. This resulted in experiments getting rerun multiple times when PRs got merged right after each other before the rerun had completed.
This was especially a problem when defaults got changed since that affected a lot of experiments, costing money.
With this change experiments affected by a change in defaults will only get rerun during nightly runs. Which I think is fine
cc @danielkberry
> Rerun only experiments changed in PR

- jetstream/abouthome-startup-cache-3.toml
Execution of that data source was taking too much time (had to join crashes to pings which was very expensive)
> Removed metrics from `crash_hour` data source

- jetstream/abouthome-startup-cache-3.toml
This experiment was attempted to be rerun yesterday but was affected by a CI bug where it did not actually rerun. This was recently fixed, so I'm triggering the rerun again
> Rerun `abouthome-startup-cache-3` experiment

- jetstream/import-bookmarks-image-and-segmentation-de.toml
- jetstream/import-bookmarks-image-and-segmentation-en.toml
- jetstream/import-bookmarks-image-and-segmentation-fr.toml
Hi, 
PR to incorporate additional import metrics for the following experiments:
https://experimenter.services.mozilla.com/nimbus/import-bookmarks-image-and-segmentation-fr/summary
https://experimenter.services.mozilla.com/nimbus/import-bookmarks-image-and-segmentation-de/summary
https://experimenter.services.mozilla.com/nimbus/import-bookmarks-image-and-segmentation-en/summary
The following metrics are being added: imported_logins, imported_bookmarks, imported_history
> Add toml files for import bookmarks image localized experiments

- jetstream/persist-search-term-staged-rollout-phase-1.toml
This experiment has never been launched, but jetstream is picking it up for analysis due to Experimenter exposing it as a real experiment.
> Skip experiment

- jetstream/colorways-expiring-fx108.toml
Add firefox view opened metric to experiment jetstream config file for colorways expiry
> Add colorways expiry jetstream config file

- definitions/firefox_desktop.toml
Adds definitions for desktop DAU and DAU 28MA.
I added more context around metric ownership in the description because we want to have clear signposts for issues with these metrics, and it seems like the `owner` field is not rendered on [mozilla.github.io](https://mozilla.github.io/metric-hub). Please let me know if there's a better way to make ownership/contact information available.
Ticket: https://mozilla-hub.atlassian.net/browse/DS-2680
> add Desktop DAU and DAU 28MA

- definitions/fenix.toml
- definitions/firefox_desktop.toml
- definitions/firefox_ios.toml
- definitions/focus_android.toml
- definitions/focus_ios.toml
Ticket: [DS-2680](https://mozilla-hub.atlassian.net/browse/DS-2680)
This adds product-specific DAU metrics for the four mobile products that contribute to our Mobile KPI: Fenix, Firefox iOS, Focus Android, and Focus iOS.
Note that the retention period on `focus_android.baseline` is currently only 180 days, but [there's an open ticket to expand that to 760 days](https://bugzilla.mozilla.org/show_bug.cgi?id=1828666). When calculating DAU for reporting, we've been using `focus_android.baseline_clients_daily` instead of `focus_android.baseline`:
```sql
SELECT submission_date,
COUNT(1) AS dau
FROM focus_android.baseline_clients_daily
WHERE submission_date >= start_date
AND (isp != 'BrowserStack' OR isp IS NULL)
GROUP BY 1
```
But for the purpose of experiments -- which Metric Hub is most …
> add mobile DAU definitions

- definitions/firefox_desktop.toml
- definitions/firefox_ios.toml
- definitions/focus_android.toml
- definitions/focus_ios.toml
- Add `submission_date_column` to `baseline_v2` data sources in for KPI-relevant mobile products.
- Add `submission_date_column` and `client_id_column` to `data_sources.clients_daily` for `firefox_desktop`.
> add `submission_date_column` and `client_id_column`

- definitions/cross_product.toml
- definitions/fenix.toml
- definitions/firefox_desktop.toml
- definitions/firefox_ios.toml
- definitions/focus_android.toml
- definitions/focus_ios.toml
- definitions/multi_product.toml
Makes several changes to the DAU definitions to simplify definitions and improve discoverability for the five products that contribute towards DAU: Firefox Desktop, Fenix, Firefox iOS, Focus Android, and Focus iOS.
Changes
- Added a `daily_active_users` and `client_level_daily_active_users` metric for each of the five relevant products.
- `daily_active_users` is simply the sum of DAU in the `active_users_aggregates` table; this is the version of DAU that should generally be used for reporting.
- `client_level_daily_active_users` is a version of DAU that provides client-level information. This is not used for reporting and is not guaranteed to be exactly equal to `daily_active_users` for any product on a particular date.
- Added `data_sources.active_users_aggregates` for each product; the …
> add and update DAU definitions

- jetstream/outcomes/firefox_desktop/networking.toml
The Network/Security/Privacy teams would like to create a shared outcome tracking network layer metrics including Necko, TLS, and NSS.
I've created this outcome as a starting point.
> Added Networking outcome and starter metrics

- jetstream/introduce-addons-in-aboutwelcome.toml
adding 2 custom metrics to measure addon count as well as addon count from AMO collection. addon count takes the max number of `addons_count_mean` from clients daily; addons count from amo collection checks if an addon installed from the AMO collection provided in NUO is installed
> custom addon metrics for nuo introduce addons experiment

- definitions/firefox_desktop.toml
- jetstream/outcomes/firefox_desktop/sponsored_tiles.toml
Adds defaults for sponsored tiles metrics on Desktop. This will be used for the [Third Sponsored Tiles](https://mozilla-hub.atlassian.net/browse/AD-52) experiment and for ongoing experiments for Project Honeycomb.
Adds:
Metrics:
- Sponsored tiles disabled (boolean)
- Any tile dismissals (boolean)
- Total tiles dismissals (count)
- Dismissals in positions 1 and 2 (count)
Data source:
- Sponsored tiles clients daily data source
Outcomes file:
- sponsored_tiles.toml
> Add sponsored tiles metrics

- jetstream/dictionary-addon-all-users.toml
- jetstream/facebook-container-addon-early-day-us.toml
For two early user add ons experiments, I add metrics associated with the specific addons the experiments were about
> Add metrics for addon installs

- jetstream/dictionary-addon-all-users.toml
previous statistic computed bootstramp mean for a 0/1 variable which caused an error
> fix binomial computation for dict add on metric

- jetstream/extensions-migration-experiment-in-116.toml
Downsample `extensions-migration-experiment-in-116` due to memory issues. Picked `sample_id <=20` based on another custom config I found, but not sure if this should be something different.
> add enrollments query for downsampling

- jetstream/dictionary-addon-all-users.toml
we want to break down results by profile age, looking at early day users (profile age <= 28 days) vs existing users (>28 days)
> add profile age by enrollment segmentation

- definitions/fenix.toml
- definitions/firefox_ios.toml
- jetstream/on-boarding-challenge-the-default.toml
- jetstream/outcomes/fenix/onboarding.toml
- jetstream/outcomes/firefox_ios/onboarding.toml
In this PR:
- I have updated the fenix definition file to make the logic in the data source for the Onboarding CTA metrics more robust 
- Added onboarding CTA metrics in iOS definition file
- Created an onboarding outcome file for Android and updated the iOS file
- created config file ctd onboarding experiment on Android
> Onboarding outcomes, updated definition files and config for ctd

- jetstream/outcomes/firefox_desktop/upload_download_performance.toml
Comprised of histograms,
```
networking_download_throughput_http_1
networking_download_throughput_http_2
networking_download_throughput_http_3
```
And keyed histogram `http_upload_bandwidth_mbps` with keys,
```
http/1.1
h2
h3
```
> Add new outcome - http upload and download performance

- jetstream/parallel-marking-experiment.toml
Add a custom config for the parallel marking experiment which segments by OS and cpu_cores.
> Add Jetstream config for parallel-marking-experiment

- jetstream/parallel-marking-experiment.toml
Adding the following probes to the results:
'gc_sweep_ms_parent', 'gc_sweep_ms_content',
'gc_slice_count_parent', 'gc_slice_count_content',
'gc_parallel_mark_speedup_parent', 'gc_parallel_mark_speedup_content',
'gc_parallel_mark_utilization_parent', 'gc_parallel_mark_utilization_content',
'gc_parallel_mark_interruptions_parent', 'gc_parallel_mark_interruptions_content',
'gc_task_start_delay_us_parent', 'gc_task_start_delay_us_content',
> [ci rerun-skip] Add additional probes to parallel marking experiment results

- jetstream/outcomes/firefox_desktop/early_hints.toml
This consists of the keyed histograms: `eh_perf_page_load_time_ms` and `eh_perf_first_contentful_paint_ms`. For each, we are interested in the `preconnect_` key.
> Add the Early Hints-specific outcome

- definitions/monitor_cirrus.toml
- jetstream/defaults/monitor_cirrus.toml
- jetstream/definitions/monitor_cirrus.toml
I'm not sure what to try measuring, but I wanted to at least get something out there for feedback. 
- Does this look broadly correct?
- @danielkberry can you help with what the metric definition should actually be?
> [ci rerun-skip] add monitor_cirrus datasource and metric

- jetstream/speculative-connect-sockets-increased-population.toml
Workaround because custom experiment configs do not currently support overriding outcomes. Instead, we list out all of the metrics from the outcomes on the experiment, and set the `select_expression` to a no-op for metrics we don't want to compute.
> subset of outcome metrics for `speculative-connect-sockets-increased-population`

- jetstream/mobile-default-browser-homepage-banner-copy-test-ios.toml
Due to https://github.com/mozilla-mobile/firefox-ios/issues/16579 we'll need to set up the exposure to this experiment through a config file.
This was copied from the [previous experiment](https://github.com/mozilla/metric-hub/blob/main/jetstream/mobile-default-browser-cta-copy-test-ios.toml) and I've tested the query and confirmed with the Experimenter team that this config file won't conflict with the outcomes that have been set up trough the UI.
> Exposure event for default browser banner

- jetstream/monitor-test-production.toml
Cirrus experiments require some updates to Experimenter, so in the meantime for testing purposes, this adds a retroactive end to enrollment for the monitor experiment.
> add enrollment end date and period for monitor-test-production

- definitions/firefox_desktop.toml
Unnesting the results makes it more convenient to define metrics filtering on a result type.
> Add unnested version of Urlbar Events table

- definitions/firefox_desktop.toml
Currently, the `newtab_interactions` data source uses the Glean `client_id` column. This will result in all 0 values for `newtab_interactions` metrics when Jetstream attempts to join to the enrollments table.
> Use legacy client_id in newtab_interactions

- jetstream/mobile-default-browser-homepage-banner-copy-test-ios.toml
[This experiment](https://experimenter.services.mozilla.com/nimbus/mobile-default-browser-homepage-banner-copy-test-ios/summary) was initially set up as 28 days **total**, but given that the PM is interested in 4th week retention we need to run it for 28 days after enrollment ends.
This PR it to overwrite the config date that was originally set.
> Update end date for iOS default browser experiment

- jetstream/bookmarks-toolbar-default-on.toml
This experiment has errors in analysis like `Scalar subquery produced more than one element`, so I rearranged the scalar subquery in the metrics causing the errors. Please take a look in case something looks off.
Also just wanted to confirm: are `'bookmarks-bar_pinned_on'` and `'bookmarks-bar_pinned_off'` typos? It seems odd to have a mix of hyphens and underscores, but I don't know what these keys normally look like so wanted to ask.
> fix for scalar subquery produced more than one element

- jetstream/ios-sync-manager-integration.toml
This experiment was still running until today despite ending being requested. Adding a custom config so that Jetstream doesn't needlessly compute 6 months worth of data.
> add end date in line with original duration

- definitions/firefox_desktop.toml
- jetstream/outcomes/firefox_desktop/pocket_newtab.toml
Replaces the metrics in `pocket_newtab.toml` with New Tab equivalents, where available. Currently, there is not a PREF_CHANGED event instrumented in `newtab`, so I've replaced those in the outcome file with metrics that record the pref. When the event is instrumented, these should be swapped over.
> Replace activity stream metrics with newtab

- opmon/desktop-dau.toml
depends on https://github.com/mozilla/opmon/pull/173
We can set `client_id_column` to `NULL` if metrics or datasources should ignore client ID ([see](https://github.com/mozilla/metric-hub/blob/aae373bf2d2f29092e03154fae47917cc17a8415/definitions/multi_product.toml#L54)). We should do the same for the OpMon desktop DAU config
There is a preview here: https://mozilla.cloud.looker.com/dashboards/operational_monitoring::opmon_preview?Table=%27mozdata.tmp.desktop_dau_statistics%27&Submission+Date=2023-11-24+to+2023-11-28&Metric=%22kpi_forecast%22&Statistic=mean
> Use NULL client_id_columns for desktop DAU

- jetstream/mobile-default-browser-homepage-banner-copy-test-ios.toml
I was using the wrong message key for this experiment. This is the correct key.
> Fix message key for default-browser-eco-copy

- jetstream/review-checker-119-existing-user-profiles.toml
- jetstream/review-checker-119-new-profiles.toml
This change is temporarily necessary in order to deliver experiment results in time for the 12/7 go/no-go decision meeting. This change should be reverted on 12/7 after that meeting in order to deliver full results on 12/8, though this can happen as a manual verification (does not need to be done through metric-hub) as that would save on the costs of doing a full rerun.
> Updates measurement period for RC experiments

- jetstream/outcomes/firefox_desktop/firefox_suggest.toml
Add count and proportion of urlbar impressions ending on a SERP (computed from the urlbar events data source).
> Add metrics to suggest outcome

- jetstream/firefox-view-update-experiment.toml
Previous exposure signal definition relies on telemetry that seems to be broken for control. updating the config file with new exposure signal to account for this
> change exposure signal to working telemetry

- jetstream/cbhqps-german-hold-back-mobile-android.toml
Due to low enrollment upon release of new version, we extended the enrollment period, and also increased the observation period to match desktop.
> Update dates for CBH/QPS German Hold-back (Mobile-Android)

- definitions/firefox_desktop.toml
- jetstream/bookmarks-toolbar-default-on.toml
- jetstream/bug-1698297-pref-fission-m7-beta-experiment-beta-88-89.toml
- jetstream/bug-1706428-pref-fission-m7-beta-experiment-with-memory-filter-beta-89-91.toml
- jetstream/bug-1712979-pref-fission-beta-90-experiment-beta-90-91.toml
- jetstream/bug-1719576-pref-fission-beta-91-experiment-beta-91-91.toml
- jetstream/bug-1722112-pref-fission-process-count-nightly-92-94.toml
- jetstream/bug-1722551-pref-full-js-parsing-experiment-nightly-94-94.toml
- jetstream/bug-1724054-pref-fission-beta-92-experiment-beta-92-92.toml
- jetstream/bug-1725055-pref-fission-release-92-experiment-release-92-92.toml
- jetstream/bug-1727420-pref-fission-beta-93-process-count-experiment-beta-93-93.toml
- jetstream/bug-1731908-pref-fission-beta-94-95-experiment-beta-94-95.toml
- jetstream/bug-1780829-pref-impact-of-concurrent-delazification-nightly-107-107.toml
- jetstream/bug-1811065-pref-impact-of-parallel-marking-v2-nightly-111-112.toml
- jetstream/ctd-marketing-attribution.toml
- jetstream/firefox-ios-homepage-experiment-sponsored-shortcuts.toml
- jetstream/impact-of-race-cache-with-network-feature.toml
- jetstream/parallel-marking-experiment.toml
- jetstream/speculative-connect-sockets.toml
- opmon/desktop-dau.toml
In `LIKE` patterns unescaped underscores will match any single character.
> [ci skip-rerun] Escape underscores in `LIKE` patterns

- jetstream/parallel-marking-experiment-2.toml
Adding a custom jetstream config for the parallel-marking-2 experiment found here:  https://experimenter.services.mozilla.com/nimbus/parallel-marking-experiment-2/summary
> Add parallel marking 2 jetstream config

- jetstream/sponsored-suggestion-placement.toml
- Add session-based metrics
- Use segments for exposed/non-exposed rather than exposure signal
- Align metrics for comparability: tagged Google SERPs with ads loaded
- Rewrite query for urlbar sessions
> Update higher placement experiment config

- definitions/firefox_desktop.toml
Creating new data_source `[data_sources.newtab_visits_topsite_tile_interactions]` based on `newtab_visits`. Pointing most dismissal metrics to it. Also adding metrics for organic tile dismissals.
> [AD-144] Creating new data_source and pointing most dismissal metrics to it. Also new metrics for organic tile dismissals.

- definitions/fenix.toml
- definitions/firefox_ios.toml
- definitions/focus_ios.toml
- definitions/klar_ios.toml
We noticed that the search metrics for Fenix in jetstream were broken. Using the current definition (pasted below) now returns no results:
```sql
(
SELECT *
FROM `mozdata.search.mobile_search_clients_engines_sources_daily`
WHERE normalized_app_name = "Fenix"
)
```
This is because "Fenix" is no longer a value in `normalized_app_name`. I'm not sure when or where this changed, but it appears to be recent. The filter needs to be changed to either:
```sql
WHERE app_name = "Fenix"
```
OR 
```sql
WHERE normalized_app_name_os = "Firefox Android"
```
[It appears that these two filters return the same data](https://sql.telemetry.mozilla.org/queries/97049/source).
I also went ahead and changed the filters for the other apps to follow the same pattern. 
I also changed the URI count metric on fenix to …
> change search data source filters and fix fenix uri count

- jetstream/defaults/fenix.toml
Related to one of the updates in #332, this removes an expired probe from fenix defaults for experiment analysis.
> [ci skip-rerun] remove expired total uri count probe

- jetstream/android-onboarding-search-widget.toml
The last run was done while search results were missing due to the bug, with the recent fix we can now rerun this experiment.
> Triggering a rerun of the android search widget experiment

- definitions/fenix.toml
- definitions/firefox_desktop.toml
- definitions/firefox_ios.toml
- definitions/focus_android.toml
- definitions/focus_ios.toml
- definitions/multi_product.toml
This change is required to keep the client-level DAU metrics in sync with the [new Mobile DAU definition](https://docs.google.com/document/d/1-sP8F0XskeyVIXApXjWn26mpTLjvW9CQ6bQsZZoS5B4/edit#heading=h.qdndw0yzycur), which only counts users as "active" when they have a baseline duration > 0 (i.e. the app is in the foreground).
The PR also updates the DAU description links to point to Confluence, which provides richer context than DTMO.
The query below validates that this updated definition closely matches the DAU values reported in `active_users_aggregates` (some difference are expected due to Shredder).
```sql
WITH baseline AS (
SELECT DATE(submission_timestamp) AS submission_date,
COUNT(DISTINCT CASE WHEN metrics.timespan.glean_baseline_duration.value > 0
AND LOWER(metadata.isp.name) != …
```
> Adds client_level_daily_active_users_v2

- definitions/firefox_desktop.toml
This adds the new profile retention outcomes that we have agreed upon for the desktop funnel:
* repeat first month user: whether the client was DAU at least once sometime between their 2-28th days.
* retained week 4 user: whether the client was DAU at least once in their fourth week (days 22-28).
> add new profile retention outcomes

- jetstream/outcomes/firefox_ios/onboarding.toml
These metrics are defined in the Default Browser outcome as well, and one of the definitions in Onboarding are out of date. To avoid this in the future, we should remove the duplicate definitions so they can be updated in only one place.
> fix onboarding metric definition

- opmon/firefox-user-choice.toml
I overlooked this before landing.
While we're here, can we schedule this to backfill from `2023-01-01`, like it says in the TOML?  I expected that to happen last night.
> Scale Firefox set-as-default (UserChoice) metrics by 100 to account for `sample_id`

- jetstream/defaults/fenix.toml
- jetstream/defaults/firefox_desktop.toml
- jetstream/defaults/firefox_ios.toml
- jetstream/defaults/focus_android.toml
- jetstream/defaults/focus_ios.toml
Pre-enrollment bias is a form of "randomization failure" where, due to chance, branches have observed differences in metrics from pre-experiment periods. Since during-experiment behavior for a client is highly dependent on their pre-experiment behavior, these failures can invalidate simple experiment analyses and require complex or impossible corrections.  Randomization guards against this by making such differences _unlikely_, but does not completely prevent them. For any given experiment, the odds of experiencing this failure are low, but for our growing experiment platform, we will encounter these with increasing frequency. 
Upstream dependencies for this PR have been met in: 
* https://github.com/mozilla/metric-config-parser/pull/353 
* Adds the pre-enrollment analysis periods and …
> [ci skip-rerun] Enable pre-enrollment bias monitoring

- jetstream/defaults/fenix.toml
> [ci skip-rerun] fix: update jetstream defaults to use non-deprecated search count

- definitions/firefox_ios.toml
- jetstream/ios-search-bar-placement-impact-assessment.toml
`firefox_ios.new_profile_activation` has been replaced by a more reliable `firefox_ios.clients_activation`. This is just a follow up to that change to make sure the correct table is used.
blocks: https://github.com/mozilla/bigquery-etl/pull/5149
> feat(DENG-2431): Update new_profile_activation source definition to point to the new activation table

- definitions/firefox_desktop.toml
Update new tab metrics that are not position-based to pull from `newtab_clients_daily`
> Point new tab metrics to clients daily

- jetstream/sponsored-suggestion-placement-phase-2.toml
Read through https://mozilla.slack.com/archives/CF94YGE03/p1711033682724839 and some of the relevant Experimenter docs. This should be in the spirit of producing two cohorts for analysis.
* Ran `jetstream validate_config ...`, but it's giving the issue and I'd like y'all's help to debug:
```Column name enrollment_date is ambiguous```
> [RS-1063] Adding custom config for 'sponsored-suggestion-placement-phase-2'

- jetstream/ios-felt-privacy-simplified-nav-and-felt-deletion-v2.toml
The enrollment table caused the pipeline to break and so I am removing it at the expense of being able to filter out clients that were enrolled in both control and test branches. I am comfortable with it because they are very small proportion of the exposed population
> removing the enrollment table from the query

- opmon/firefox-ios-health.toml
Adding the cpu-exception metric to the firefox-ios-health dashboard.
> Add cpu exception metric

- opmon/firefox-ios-health.toml
Updated the cpu exception and large file write metrics to use ratios instead.
Removed the total baseline pings and dirty_startup sum visualizations, there should just be 3 charts on the dashboard now. Please let me know if that is not the correct way to achieve that change.
> Update all metrics on ios health to use ratios

- opmon/firefox-ios-beta-health.toml
Adding a copy of the firefox-ios-health dashboard to observe the beta channel only.
> Add ios beta health dashboard in opmon

- .script/validate.py
- lib/metric-config-parser/metric_config_parser/templates/data_source_macros.j2
- lib/metric-config-parser/metric_config_parser/tests/sql/test_generate_data_source_with_join.expected.sql
- lib/metric-config-parser/metric_config_parser/tests/sql/test_generate_data_source_with_multi_join.expected.sql
- lib/metric-config-parser/metric_config_parser/tests/sql/test_generate_query_with_joined_data_sources.expected.sql
- lib/metric-config-parser/setup.py
- looker/definitions/firefox_desktop.toml
This adds some desktop engagement OKR metrics as a proof-of-concept based on this Looker view: https://github.com/mozilla/looker-spoke-default/pull/846
> Add some OKR metrics to Looker

- jetstream/outcomes/firefox_desktop/firefox_suggest.toml
Update naming to be consistent with the terminology we've been using recently. Simplify select expressions against urlbar events table.
> Update naming and queries for urlbar metrics

- looker/definitions/ads.toml
Reverts mozilla/metric-hub#487
Sorry, reverting this as the table doesn't seem to exist and breaking looker generation
> Revert "Generated Looker explore for PPA conversions"

- jetstream/defaults/fenix.toml
- jetstream/defaults/firefox_desktop.toml
- jetstream/defaults/firefox_ios.toml
- jetstream/defaults/focus_android.toml
- jetstream/defaults/focus_ios.toml
Reverts mozilla/metric-hub#491
> [ci skip-rerun] Revert "[ci skip-rerun] Enable linear-model based mean inferences"

- jetstream/defaults/fenix.toml
- jetstream/defaults/firefox_desktop.toml
- jetstream/defaults/firefox_ios.toml
- jetstream/defaults/focus_android.toml
- jetstream/defaults/focus_ios.toml
Reverts mozilla/metric-hub#498. 
When we previously pushed this, we encountered some errors. Those were largely fixed in https://github.com/mozilla/mozanalysis/pull/266. However, when an experiment is rerun, there is now a race condition between the analysis periods. Later analysis periods (e.g., week & overall) will depend on prior analysis periods (i.e., preenrollment_week) which may or may not have completed. In the case where covariate adjustment using preenrollment_week was specified but preenrollment_week is not available, we will now fall back (https://github.com/mozilla/mozanalysis/pull/268) to unadjusted inferences and emit a warning.  Since these improvements are now in Jetstream (https://github.com/mozilla/jetstream/pull/2085), we can attempt to reenable the inferences. 
Once …
> [ci skip-rerun] re-enable covariate adjustment

- definitions/firefox_desktop.toml
- jetstream/outcomes/firefox_desktop/pdf_handler.toml
added metrics for when firefox was invoked or launched and created a new outcome with those metrics.  this work completes the second request in this [ticket](https://mozilla-hub.atlassian.net/browse/DS-3669).
> added pdf handler metrics and outcome

- definitions/firefox_desktop.toml
fixing the pdf handler metric definitions in firefox_desktop.toml.
> fix desktop toml defs

- definitions/klar_android.toml
- definitions/klar_ios.toml
The `active_users_view` for Klar products currently has the filter `is_mobile`. However, Klar is not included as a mobile KPI product, so `is_mobile` will always be `false`.
This PR changes the filter to "Klar iOS" or "Klar Android", which will filter only on valid sources of Klar client_ids (excluding BrowserStack, for example).
> Fix klar active_users data_sources

- definitions/firefox_desktop.toml
- definitions/multi_product.toml
For the 10 metrics in the [Metric Levels Taxonomy](https://mozilla-hub.atlassian.net/wiki/spaces/DATA/pages/620494911/Metrics+Inventory) this PR:
- updates their descriptions (removes email addresses, empty lines, broken links, and non-acryl/datahub
- adds their current taxonomy level
- makes sure only the current, non-deprecated KPIs are tagged as KPIs
> DS-3616 Update Metric-Hub DAU and KPI metrics

- .gitignore
- lib/metric-config-parser/README.md
- lib/metric-config-parser/metric_config_parser/experiment.py
- lib/metric-config-parser/metric_config_parser/tests/conftest.py
- lib/metric-config-parser/metric_config_parser/tests/test_experiment.py
- lib/metric-config-parser/requirements.in
- lib/metric-config-parser/requirements.txt
- lib/metric-config-parser/setup.py
- adds a `randomization_unit` property to the experiment config to make it easier to access
- adds a `analysis_unit` property to the experiment config that is derived from `randomization_unit` for use by jetstream
> feat: add support for randomization_unit and analysis_unit in experiment config

- looker/definitions/websites.toml
The marketing tables moved to shared-prod, so this needs to be updated
> Update websites definitions

- jetstream/macos-background-tab-power-savings-release.toml
i've copied over the toml from the beta jetstream/macos-background-tab-power-savings.toml to this one so the custom metrics are available for the powersaving relase experiment.  the only thing I changed from the earlier experiment toml file is the experiment name (to the current one) in the datasources select statement in line 126.  not sure if that was strictly necessary.
> macos powersaving release adding custom metrics

- .circleci/config.yml
not broken, but I had to update Jetstream's gcp-gcr orb due to circleci image expirations so thought I'd also take a look at mozanalysis and metric-hub
> chore: update path-filtering orb

- jetstream/definitions/functions.toml
- jetstream/outcomes/firefox_desktop/crlite.toml
Experiment owner requested that we use a mean here because Jetstream doesn't support histogram metrics.
Tried to follow existing usage of `agg_histogram_mean`, but not totally sure if this is correct so please check my work here!
> bug: cert_storage_memory should be histogram mean

- jetstream/outcomes/firefox_desktop/crlite.toml
Getting an error for both of these that `revocation_check_counter` doesn't exist, so guessing we just need to make sure that the `depends_on` is set so the numerator/denominator are available before computing this metric's statistic.
> bug: pop ratio metrics must specify depends_on

- looker/definitions/ads.toml
The view moz-fx-data-shared-prod.ads.consolidated_ad_metrics_hourly got updated and `creative_title` and `creative_url` got removed
> Update ads.toml - remove create_title and creative_url

- jetstream/outcomes/firefox_desktop/content_process_stability.toml
- jetstream/outcomes/firefox_desktop/main_process_stability.toml
We want to monitor crash metrics for content and main processes for the USER_RESTRICTED experiment. There's a fair chance that these metric groupings will be useful for other experiments, so I'm adding them as outcomes.
> Add crash metric outcomes for USER_RESTRICTED

- jetstream/new-alt-text-flow-and-generation.toml
[Experiment Brief](https://docs.google.com/document/d/1SVgFBFSv4oxNFRyCyBbpsMc65UQIq-RqJiodQJW-e84/edit)
This config file sets exposure to users who started the flow to add an image in the PDF editor and creates metrics for number of images added and ratio of those images that contain alt text.
> Config file for New alt text flow and alt text generation in PDF Editor experiment

- lib/metric-config-parser/metric_config_parser/config.py
- lib/metric-config-parser/metric_config_parser/tests/integration/test_config_integration.py
- lib/metric-config-parser/metric_config_parser/tests/test_config.py
- lib/metric-config-parser/pyproject.toml
Added a new function in metric-config-parser that retrieves and returns all available segments based on application.
> Implement segment retrieval function in metric-config-parser

- jetstream/improved-mailto-handling-with-os-integration.toml
downsample treatment-a branch to bring it in line with other branches and so that we can hopefully prevent memory issues
> downsample treatment-a branch

- lib/metric-config-parser/metric_config_parser/config.py
- lib/metric-config-parser/metric_config_parser/tests/test_config.py
- lib/metric-config-parser/pyproject.toml
* Adds a `from_local_path` function to `ConfigCollection`
* bumps version to 2024.11.1
Why? Experimenter wants to use metric-config-parser to parse a partial local copy of metric-hub for outcomes and segments, and the existing `from_local_repo` required some mock objects in order for the local copy to work as a git repo (Experimenter always wants the latest version, so has no need for the `.git` dir that is used to get configs from a specific date, and `.git` is kind of big!).
Related: https://github.com/mozilla/experimenter/pull/11772
> feat: create ConfigCollection from non-git path

- definitions/firefox_desktop.toml
- jetstream/defaults/firefox_desktop.toml
* change the default DAU metric for experiments to the non-deprecated `_v2` version
* also matches with mobile, which is helpful for changing the guardrails in Experimenter
* skip rerunning jetstream for all desktop experiments
> [ci skip-rerun] fix: change desktop default DAU metric to v2

- definitions/firefox_desktop.toml
- jetstream/desktop-feature-callout-signed-into-account.toml
- jetstream/desktop-to-mobile-adoption-promo-signed-into-account-eu.toml
add custom configs to desktop-feature-callout-signed-into-account and desktop-to-mobile-adoption-promo-signed-into-account-eu experiments
> Mobile adoption promo configs

- jetstream/certificate-transparency.toml
Adding this filter cuts the bytes processed estimate down by ~40x, so hopefully this will take care of the resource issues we were seeing.
Of note, this same data source is also defined in an outcome [here](https://github.com/mozilla/metric-hub/blob/main/jetstream/outcomes/firefox_desktop/networking.toml#L385-L402) (er, kind of twice), so we should consider putting this into the base desktop definitions.
> add and use filtered events datasource

- jetstream/certificate-transparency.toml
Just tested this experiment slug filter and it seemed to run ok, so let's try this.
Also, doing rerun-skip and I'll just manually rerun the couple of dates that failed last time.
> [ci rerun-skip] certificate-transparency: add exp filter to tls_metrics ds

- looker/definitions/ads.toml
Data stopped showing after merging join. Rolling back join but leaving new ratio metrics. Should clean up redundant names later on.
> Rolling back desktop native join

- jetstream/certificate-transparency.toml
changed tls timing data source to use legacy client id in experiment toml file.  also removed division in metric 'from' statement since that is what worked in our test query.
> [ci rerun-skip] certificate-transparency: use legacy id for tls timing

- jetstream/certificate-transparency.toml
add number of handshakes and timing ratio metrics, aggregate statistics daily, and also add deciles.
> [ci rerun-skip] certificate-transparency: add timing ratio metrics and deciles

- jetstream/certificate-transparency.toml
adjusting select statement and pretretment for tls_ratio statistic to ignore nulls so we don't divide by zero
> [ci rerun-skip] certificate-transparency: remove nulls from tls ratio

- opmon/firefox-ios-health.toml
A fix for the tab loss event on the iOS health dashboard. I previously forgot to filter based on the event name 🙈
> Add event name condition

- jetstream/outcomes/firefox_desktop/relay.toml
An error during automated analysis computing `relay_optin_rate` and `relay_optin_disabled_rate` indicated that one of the ratio metrics was not found, and it seems that this was a simple typo in the denominator metric name for a couple statistics.
* fixed the typos
* auto-formatted the TOML file
> fix: typos in denominator metric

- definitions/fenix.toml
promote-add-ons-in-onboarding-release had an issue with resources during analysis, and I noticed this datasource includes two UNNESTs and a JOIN within the expression. I created a new DS using events_stream instead of events, which removes the need for the UNNESTs, and drastically reduces data scanned.
Not sure if this will completely resolve the issue, but it should at least make for a much simpler query for the affected metrics, and we can iterate from there.
> feat: add special_onboarding_events_v2 ds using events_stream

- definitions/firefox_ios.toml
> fix: make sure we only take only rows corresponding to new profiles

- .circleci/validation-config.yml
- lib/metric-config-parser/pyproject.toml
forgot to bump version with last change
Edit to add:
There was a dependency resolution issue in CI that a) I don't know why it popped up now with this version change, and b) was fixed when upgrading pip. This issue was fixed by explicitly upgrading pip during the build step in CI.
> chore: version 2025.3.1

- opmon/new-toolbar-ios-ios-redesign-beta-rollout.toml
Skip due to it breaking Looker generation: https://workflow.telemetry.mozilla.org/dags/looker/grid?search=looker&dag_run_id=manual__2025-03-31T06%3A39%3A23.046259%2B00%3A00&task_id=lookml_generator_staging&tab=logs
The rollout is misconfigured and was replaced by `new-toolbar-ios-ios-redesign-beta-roll-out`
> Skip new-toolbar-ios-ios-redesign-beta-rollout

- jetstream/address-bar-update-donoharm.toml
https://mozilla-hub.atlassian.net/browse/DS-4216
https://docs.google.com/document/d/1LuF0zYrnOQQThrAsJUcj7_SirJx-zu0tyuv0vIAgUfc/edit?tab=t.0
I added two metrics to this custom config. Some questions:
1. `search_engine_default_change` metric uses glean events stream as a data source, should I filter this data source further to `event_category = 'search.engine.default'` for computational purposes?
2. for the metric `non_default_search_engine_search` I had to UNNEST a field in the metrics glean table and denote it as a data source, is this viable?
Thanks!
> add custom config for success metrics

- jetstream/ios-sent-from-firefox.toml
For [DS-3907](https://mozilla-hub.atlassian.net/browse/DS-3907) - Sent from Firefox - iOS
Query to reproduce logic:
```sql
WITH events AS (
SELECT
event_timestamp,
event_extra,
JSON_VALUE(event_extra["activity_identifier"]) AS activity_identifier,
JSON_VALUE(event_extra["share_type"]) AS share_type,
JSON_VALUE(event_extra["is_enrolled_in_sent_from_firefox"]) AS enrolled,
JSON_VALUE(event_extra["is_opted_in_sent_from_firefox"]) AS opted_in,
client_id AS client_id
FROM
`mozdata.org_mozilla_ios_firefox.events_stream`
WHERE
DATE(submission_timestamp) >= DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY)
AND event = 'share_sheet.shared_to'
AND event_category = 'share_sheet'
)
-- Summarize metric logic
SELECT
COUNTIF(
share_type = 'tab'
AND enrolled = 'true'
AND opted_in = 'true'
) AS total_tab_shares, …
```
> add toml file

- jetstream/shortcuts-visual-refresh.toml
Per request from experiment owner
/cc @ilanasegall
> add sponsored tiles outcome metrics to shortcuts-visual-refresh

- jetstream/outcomes/fenix/awesomebar.toml
the event category of the Fenix awesomebar metrics changed. that broke the outcome for this experiment: https://experimenter.services.mozilla.com/nimbus/encourage-use-of-search-bar-on-mobile/summary
im electing not to rename anything else here because i don't want to break the pointers for that experiment (not sure that would happen, but to be on the safe side)
> change source of fenix awesomebar outcomes

- jetstream/outcomes/fenix/default-browser.toml
- the `events` data_source is unfiltered and uses the events table which requires a CROSS JOIN to unnest the event info, and `events_stream` is recommended as an alternative wherever possible
- this outcome appears to be causing an issue with a few experiments timing out in metric queries
> feat: refactor default browser outcome to use filtered events_stream

- jetstream/address-bar-update-donoharm.toml
- jetstream/address-bar-update-launch-extention.toml
Adds the requested segments from [DS-4258](https://mozilla-hub.atlassian.net/browse/DS-4258?linkSource=email) to the experiment configs.
Changes the end date to today (2025-05-02) to trigger Jetstream analysis to run tonight.
> [DS-4258] add segment definitions to address bar configs

- definitions/firefox_desktop.toml
- jetstream/tab-groups-10-experiment-with-onboarding.toml
Previous definition was returning the error
```
SELECT list expression references column submission_date which is neither grouped nor aggregated 
```
Updating to fix the error and adding it to the Tab Groups experiment.
> Fix desktop new profiles segment

- lib/metric-config-parser/metric_config_parser/data_source.py
- lib/metric-config-parser/metric_config_parser/metric.py
- lib/metric-config-parser/metric_config_parser/tests/test_analysis.py
- lib/metric-config-parser/pyproject.toml
Only desktop has groups, so we should only default to assuming support for both client and group in desktop, and only client otherwise.
> feat: set default analysis_units by app

- jetstream/sent-from-firefox-android-1-rollout.toml
- jetstream/sent-from-firefox-android-full-experiment-20.toml
Add metrics for the "Sent from Firefox Android" experiments -- [DS-4050](https://mozilla-hub.atlassian.net/browse/DS-4050).
> Add metrics for sent-from-firefox-android experiments

- jetstream/whats-new-notification-sidebarvertical-tabs.toml
Adds custom enrolment query due to enrollment happening in the [background update task profile](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop_background_update?itemType=pings&page=1).
Copy paste from another Background Task experiment - [backgroundtaskmessage-notification-release-4pct-en](https://github.com/mozilla/metric-hub/blob/cd6e09a1362cb564f719479c90ade9afb53e90a8/jetstream/backgroundtaskmessage-notification-release-4pct-en.toml#L38)
[Experiment brief](https://docs.google.com/document/d/1RtRAwI0rh3SAuFosmAAQ_iVX40ZD2f_bfLgzbnBw2kc/edit?tab=t.0)
[Experiment](https://experimenter.services.mozilla.com/nimbus/whats-new-notification-sidebarvertical-tabs/summary)
[Original enrollment query](https://sql.telemetry.mozilla.org/queries/107085/source)
> [jetstream] Adds enrollment query for Whats New Notification Sidebar/Vertical tabs experiment

- jetstream/whats-new-notification-tab-groups.toml
Adds custom enrolment query due to enrollment happening in the [background update task profile](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop_background_update?itemType=pings&page=1). Same query as https://github.com/mozilla/metric-hub/pull/921
[Experiment brief](https://docs.google.com/document/d/1OVNugPsnWXXF1XCFIHMOsDlmZ5UkGLqi96zGVoCj_bc/edit?tab=t.0#heading=h.fcnbbybcfpfg)
[Experiment](https://experimenter.services.mozilla.com/nimbus/whats-new-notification-tab-groups/summary)
> [jetstream] Adds enrollment query for Whats New Notification Tab Groups

- lib/metric-config-parser/metric_config_parser/data_source.py
- lib/metric-config-parser/pyproject.toml
@relud recently added support for `events_stream` as an `experiments_column_type`, but in order to configure that it needs to be in metric-config-parser as well. This adds that support (along with doc update).
> feat: add support for new events_stream experiments_column_type

- jetstream/1-callout-contextual-chatbot-suggestion.toml
Required due to [simplified onboarding rollout](https://experimenter.services.mozilla.com/nimbus/simplified-chatbot-onboarding-short-copy-1-step-rollout/summary)
> Chatbot Continue event as completed

- looker/definitions/firefox_desktop.toml
Creating metrics for the Ads Program Health monitoring dashboard - sponsored ads per client, and sponsored tiles per client, and ads per client.
> create ad-per-client metric

- looker/definitions/ads.toml
Adding median and p95 as metric to HNT visit duration after raising concerns about the right-skewness of distribution and the larger-than-expected averages.
> Adding median and p95 to hnt visit duration

- definitions/ads.toml
- looker/definitions/ads.toml
- looker/definitions/firefox_desktop.toml
The problem with these statistics was that we weren't able to surface the metric before, the `depends_on` functionality was not yet live so this is a workaround to surface the metrics so we can create ratio statistics with them. The reason to go this route and not just name the ratio after the numerator is because we have some ratios that use the same numerator and would not be able to share a name. Some naming conventions though are actually commonly used, like clicks.ratio is common for CTR, so those seemed ok to keep. 
My general approach was to only use SUM(1) in the looker layer metric definitions because it's solely for looker purposes. 
For the future, if `depends_on` does become live, we can change all SUM(1) instances back to `depends_on`
> Fix ratio statistics naming and remove unused metrics

- .script/generate_docs.py
- lib/metric-config-parser/metric_config_parser/data_source.py
fixes https://github.com/mozilla/metric-hub/issues/995
`DataSource`s are no longer hasheable, so to get unique data sources the `generate_docs` script builds a dict
> Fix build docs

- .circleci/validation-config.yml
https://mozilla-hub.atlassian.net/browse/DENG-9079
Jestream and OpMon will use the moz-fx-data-shared-prod dryrun function for validation in CI. This function requires authentication.
> [DENG-9079] Use moz-fx-data-shared-prod dryrun function for validation + authenticate in CI

- jetstream/perplexity-secondary-search-initial-part2.toml
- jetstream/perplexity-secondary-search-initial.toml
creating a non operational data set and overrideing serp_impressions metric with that data set and new def so it won't cause timeout issues for the perplexity experiments.  Following instructions from @mikewilli in [this thread](https://mozilla.slack.com/archives/CF94YGE03/p1752162164042099?thread_ts=1752161772.480129&cid=CF94YGE03).
> add no-op data source and metric

- jetstream/outcomes/firefox_desktop/firefox_suggest.toml
- jetstream/search-result-de-duplication.toml
Removing all the `analysis_units` params from metrics, turns out they're not needed there.
> remove analysis units where not needed

- jetstream/perplexity-secondary-search-initial-part2.toml
added smaller glean data sources to the toml file for second perplexity experiment to try to prevent experiment analysis timeout issues.
> add custom glean data sources

- jetstream/address-bar-update-launch-hold.toml
added a no-op for the SERP metrics with GroupID
> [ci rerun-skip] no-op serp metric for address-bar-update-launch-hold

- jetstream/intreaction-frecency-enhancement.toml
noop for SERP and sponsored tile metrics that are causing issues.  
added exposure signal and history metrics that were missing
> [ci rerun-skip] no-op serp/suggest metrics in intreaction-frecency-enhancement

- definitions/ads.toml
As part of https://mozilla-hub.atlassian.net/browse/AD-972, deprecating revenue.admarketplace in favour of ads.admarketplace. 
BTW the CI fails on this known issue: https://mozilla-hub.atlassian.net/browse/DENG-9375
> update admarketplace metrics to use ads.adm instead

- jetstream/traffic-impact-study-1.toml
- jetstream/traffic-impact-study-2.toml
- jetstream/traffic-impact-study-3.toml
Updated custom configs for these experiments ([traffic-impact-study-1](https://experimenter.services.mozilla.com/nimbus/traffic-impact-study-1), [2](https://experimenter.services.mozilla.com/nimbus/traffic-impact-study-2/summary/), [3](https://experimenter.services.mozilla.com/nimbus/traffic-impact-study-3/summary/)) removing the following metrics so we can rerun the results on a smaller subset of relevant metrics.
- sponsored_tiles_dismissals
- any_sponsored_tiles_dismissals
- sponsored_tiles_dismissals_pos1_2
> [ci rerun-skip] Removed dismissal metrics since the used newtab_visits datasource.

- .script/generate_docs.py
- .script/templates/metrics.md
As an example, here's what one of the metric's markdown looks like:
```
**URIs visited**
Counts the number of URIs each client visited
Data Source: [`baseline`](https://mozilla.github.io/metric-hub/data_sources/fenix/#baseline)
<details>
<summary>Definition:</summary>
```sql
SELECT
{{agg_sum("metrics.counter.events_normal_and_private_uri_count")}}
FROM (
(
SELECT
p.*,
DATE(p.submission_timestamp) AS submission_date
FROM `moz-fx-data-shared-prod.{dataset}.baseline` p
)
)
```
</details>
```
whereas before this change, the Definition is just 
```sql
{{agg_sum("metrics.counter.events_normal_and_private_uri_count")}}
```
fixes #1088
> feat(docs): add DS from_expr to metric docs

- .script/generate_docs.py
- .script/templates/metrics.md
Relevant part of the new metric doc markdown:
> **Definition:**
> ```sql
>{{agg_sum("active_hours_sum")}}
>```
> 
> <details>
> <summary>SQL with DataSource</summary>
> 
> ```sql
> SELECT
>   COALESCE(SUM(active_hours_sum), 0)
> FROM (
>   mozdata.telemetry.clients_daily
> )
> ```
> </details>
> feat(docs): render metric sql
