mozilla/metric-hub

definitions/firefox_desktop.toml
Added search_with_ads_organic and ad_clicks_organic as metrics.
=> add additional organic search metrics definitions

definitions/focus_ios.toml, definitions/klar_ios.toml
add several search metrics to `focus_ios`.
=> add several search metrics to `focus_ios`

jetstream/first-run-easy-as-one-click-ver-1.toml
Adding a toml for first-run-easy-as-one-click-ver-1 experiment with additional metrics to evaluate such as set_to_default_rate, taskpar_pin_rate,  and imported_bookmarks
=> first commit

jetstream/android-reengagment-notifications-release.toml
[Experiment Brief](https://docs.google.com/document/d/1ozjTysd1dLQG2tDiNkgbUnvkQiWWYxhilsyZ-RRG48k/edit#)
=> Android Re-engagment Notifications

jetstream/bug-1811065-pref-impact-of-parallel-marking-v2-nightly-111-112.toml
Experiment link: https://experimenter.services.mozilla.com/experiments/impact-of-parallel-marking-v2/
=> Add Jetstream config for parallel marking experiment

jetstream/abouthome-startup-cache-3.toml
Enrollment query will filter to data collected after the treatment has had time to be applied (ignore first 2 sessions after enrollment)
=> Add custom enrollment query

jetstream/colorways-expiring-fx108.toml
Add `have_colorways` metric to colorways expiry jetstream experiment config file
=> Add colorways have_colorways metric

jetstream/window-modal-vs-tab-modal.toml
=> Add jetstream config file for window vs. tab modal experiment

jetstream/import-bookmarks-copy.toml
include import metrics as well as is_pinned
=> add toml file for import-bookmarks-copy experiment

jetstream/fx-release-android-re-engagement-notifications-ab-experiment-v112.toml, jetstream/ios-notification-opt-in-prompt.toml
Updating the experiment dates based on when enrollment started
=> Update dates for first run mobile notification experiments

.circleci/validation-config.yml, .github/workflows/rerun-skip-comment.yml
for https://github.com/mozilla/jetstream/issues/1627
depends on https://github.com/mozilla/jetstream/pull/1714
=> [ci rerun-skip] Rerun skip support

jetstream/persist-search-term-staged-rollout-phase-1.toml
- adding new metrics that the prodcuct team would like to looks at
- updating the experiment end date
=> Persist search term new metrics

jetstream/outcomes/firefox_desktop/networking.toml
This is a key networking metric
=> Add 'time_to_response_start_ms' to the Networking outcome

opmon/network-performance-desktop-build-by-build.toml
Starting with a handful of metrics, defined in the Networking outcome
=> Added new OpMon project to monitor network performance, build by build

jetstream/dynamic-wikipedia-suggestions.toml
Fixes logic bug & adds more granular metrics.
=> Update dynamic wikipedia config

definitions/firefox_desktop.toml, jetstream/outcomes/firefox_desktop/firefox_suggest.toml
Not sure if I did it right
- Numerator listed first
- Following TOML standard: https://github.com/toml-lang/toml#example
=> Add a Population Ratio Metric

definitions/fenix.toml
this adds a boolean outcome for whether a fenix user is signed in to FxA
=> add fenix fxa metric

jetstream/release-android-onboarding-redesign.toml
[adds a config for this experiment](https://experimenter.services.mozilla.com/nimbus/release-android-onboarding-redesign/summary)
@danielkberry can you review this... im a bit rusty around these parts
=> Release android onboarding redesign

jetstream/device-migration-existing-user-multi-message-spotlight.toml, jetstream/window-vs-tab-modal-easy-set-up-fx112.toml
add 'fxa_signed_in' to device migration experiment, and 'is_pinned' to windows vs tab modal plus easy set up
=> add relevant metrics for analysis

jetstream/navigational-suggestions.toml
Update metrics definitions to include abandonments in denominators
=> Update nav suggest config

jetstream/device-migration-existing-user-multi-message-spotlight.toml
segmentation of results by profile age
=> segment results by profile age

jetstream/outcomes/firefox_desktop/networking.toml
=> Networking outcome cross channel support

definitions/fenix.toml, jetstream/outcomes/fenix/onboarding.toml
=> Fennix onboarding cta fix

definitions/firefox_ios.toml, jetstream/outcomes/firefox_ios/onboarding.toml, jetstream/release-ios-on-boarding-challenge-the-default-copy.toml
I updated the logic in the definition file and created overrides for the enrollment dates
=> Ios ctd onboarding

jetstream/ctd-marketing-attribution.toml
The config for desktop onboarding test. The query was built by message center engineers
=> desktop config

opmon/firefox-messaging-system.toml
=> Bug1843406 messaging system tweaks

jetstream/vpn-moments-page-july-release-v2.toml
=> Create vpn-moments-page-july-release-v2.toml with downsampling

jetstream/pin-to-taskbar-context-early-day-users.toml, jetstream/set-to-default-context-early-day-users-fox-doodle.toml
add login, bookmark and login imports as well as is pinned metrics to pin/set to default early user day fox doodle experiments
=> add imports and is pinned metrics

definitions/fenix.toml, opmon/android-add-ons-extension-process.toml, opmon/definitions/fenix.toml
Adding memory metrics for `android-add-ons-extension-process` rollout
=> Custom config for android-add-ons-extension-process

definitions/firefox_desktop.toml, jetstream/outcomes/firefox_desktop/newtab_do_no_harm.toml
Added organic tiles click and impression metrics, added them to do no harm outcome.
=> Update do no harm outcome

jetstream/outcomes/firefox_desktop/page_load_performance_minimal.toml
Add a new "minimal" page load performance outcome with only the essential performance probes.
=> Add a minimal performance outcome with fewer probes

jetstream/outcomes/firefox_desktop/networking_performance.toml
Just the performance metrics from the Networking outcome.
=> Create a minimal networking performance outcome

definitions/firefox_ios.toml
This is to merge funnel metrics definition in metrics hub
=> funnel metrics definition in metric hub

opmon/garbage_collection.toml
This is my first try with metric hub, so please give me all the feedback :) 
There is no real use case yet and the idea is mostly to get a feel for OpMon and go from there. 
I did not find the metric `gc_effectiveness` in the defaults and I'm not sure if it would be better to add it to the firefox_desktop defaults or put it here as a one off ...
=> Garbage collection

definitions/fenix.toml, definitions/firefox_ios.toml, jetstream/defaults/fenix.toml, jetstream/defaults/firefox_desktop.toml, jetstream/defaults/firefox_ios.toml, jetstream/firefox-accounts-toolbar-button-default-visibility-part-2.toml
Adds initial attempt for fx desktop
=> [ci skip-rerun] Adds DAU as a metric

jetstream/speculative-connect-sockets-increased-population.toml
=> Sample speculative-connect-sockets-increased-population.toml

definitions/firefox_desktop.toml
Adds minimal `new_profiles` metric
=> DENG-1612 - Added new_profiles metric

jetstream/bookmarks-toolbar-default-on.toml
config file for https://experimenter.services.mozilla.com/nimbus/bookmarks-toolbar-default-on/summary
=> add config for bookmarks toolbar experiment

opmon/defaults/monitor_cirrus.toml
fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1862952
=> Add Opmon defaults for monitor_cirrus

jetstream/firefox-view-update-experiment.toml
jetstream is having computation issues with the amount of data for this experiment. downsampling and removing 4 metrics for ease of computation
=> downsample further to 30 percent, remove metrics

jetstream/firefox-view-update-experiment.toml
limit data source events to events_category = 'firefoxview_next'
=> limit data source events

opmon/mozilla_vpn.toml
=> Ds 3276 mozilla vpn dashboard

jetstream/homepage-banner-add-ons-reminder-test-android.toml
[Experiment brief](https://docs.google.com/document/d/1PipXb0yWflQiSFESpRN4z0vVDZQ4Aj5qJaZgPIaSpVU/edit)
=> Add-ons homepage banner

jetstream/cbhqps-german-hold-back-mobile-android.toml
[Experiment Brief](https://docs.google.com/document/d/1IhX_drzmGhO6vedQUsgWJ5s7wLlCDqi-EFX1jlkAVRE/edit)
=> CBH Android Holdback DE

jetstream/device-migration-q4-spotlights.toml
adding 2 metrics:
1. fxa sync
2. sync more than 1 desktop device
=> add device migration q4 spotlights sync metrics

jetstream/new-user-test-copy-about-privacy-speed-security-fr-it-de-fx119.toml
segment by DE, FR, and IT locales
=> include locale segmentation

definitions/firefox_desktop.toml, jetstream/outcomes/firefox_desktop/newtab_do_no_harm.toml
Adds updates to the Do No Harm metrics and outcome based on [this doc](https://docs.google.com/document/d/1FZX1spwPXi5uHl_r5gMZWBtNWbwPkmhvSCqhdLhhKiY/edit).
=> Updates for New Tab Do No Harm

.circleci/config.yml, .circleci/validation-config.yml, .script/validate.py, definitions/fenix.toml, definitions/firefox_desktop.toml, looker/definitions/fenix.toml, looker/definitions/firefox_desktop.toml
Some metric for demoing automatic Looker artifact generation
=> Demo fenix feature usage

jetstream/README.md, jetstream/pages-ranking-experiment-revised.toml
Fixed some old links.
Added a configuration file for a new experiment.
=> Pages ranking experiment

.script/requirements.txt
This should fix doc generation.
Fixes #380
---
Not sure if there's anything else stopping the upgrade?
=> Update mozilla-metric-config-parser to latest release

.script/requirements.txt, jetstream/defaults/fenix.toml, jetstream/defaults/firefox_desktop.toml, jetstream/defaults/firefox_ios.toml, jetstream/defaults/focus_android.toml, jetstream/defaults/focus_ios.toml
Blocked on https://github.com/mozilla/metric-config-parser/pull/365
=> [ci skip-rerun] Preenrollment name fix

jetstream/ios-felt-privacy-simplified-nav-and-felt-deletion-v2.toml
This is to upload the config file that defines the exposure signal for ios_felt_privacy_simplified_nav_and_felt_deletion_v2 experiment
=> iOS felt privacy config file upload

definitions/firefox_desktop.toml
Fixes SQL errors in New Tab metrics.
=> Update SQL statements of newtab scalars

opmon/firefox-ios-health.toml
Add hang exception metric to ios health dashboard
=> Add hang exception metric to ios health dashboard

opmon/firefox-ios-beta-health.toml
Add release dimension for ios beta
=> Add release dimension for ios beta

definitions/firefox_desktop.toml, jetstream/outcomes/firefox_desktop/pocket_newtab.toml
Adds metrics to test for changes in share of clients that have any Pocket clicks.
=> Add boolean Pocket click metric

jetstream/home-and-newtab-wallpapers-v1-highlight.toml, jetstream/home-and-newtab-wallpapers-v1-spotlight.toml, jetstream/home-and-newtab-weather-v1.toml
Configs for the following experiments:
- [Wallpaper spotlight](https://experimenter.services.mozilla.com/nimbus/home-and-newtab-wallpapers-v1-spotlight/summary)
- [Wallpaper highlight](https://experimenter.services.mozilla.com/nimbus/home-and-newtab-wallpapers-v1-highlight/summary)
- [Weather highlight](https://experimenter.services.mozilla.com/nimbus/home-and-newtab-weather-v1/summary)
=> New Tab wallpaper and weather configs

.circleci/validation-config.yml, .script/requirements.txt, .script/validate.py, definitions/klar_ios.toml
Change to using the bigquery-etl dryrun function as it has access to confidential schemas
=> Use bigquery-etl dryrun function for dryruns

lib/metric-config-parser/metric_config_parser/data_source.py, lib/metric-config-parser/setup.py
This fixes the ability to override joins
=> Fix merging joins

definitions/firefox_desktop.toml, jetstream/outcomes/firefox_desktop/pdf.toml
added pdf highlights metrics, added to pdf_engagement metric, added to pdf outcome.
=> add highlights to pdf outcome

looker/definitions/ads.toml
The Ads team would like few more columns - title, url and image in the looker dashboards for their reporting
=> Added new fields as per Ads team feedback

definitions/fenix.toml, definitions/firefox_desktop.toml, definitions/firefox_ios.toml, definitions/focus_android.toml, definitions/focus_ios.toml, definitions/klar_android.toml, definitions/klar_ios.toml
Adds client-level DAU definitions for each product as requested in [DS-3752](https://mozilla-hub.atlassian.net/browse/DS-3752).
=> update client-level DAU definitions

jetstream/android-private-window-visual-refresh.toml
android-private-window-visual-refresh jetstream config upload
=> android PWVS config upload

jetstream/us-review-checker-v2-holdback-experiment.toml
added experiment control exposure for pdp page visit and added metric to data sources
=> update toml file

.circleci/validation-config.yml, lib/metric-config-parser/pyproject.toml, lib/metric-config-parser/requirements.in, lib/metric-config-parser/requirements.txt
should fix https://app.circleci.com/pipelines/github/mozilla/metric-hub/2357/workflows/8729f274-d5b3-452a-be1c-7c526a87cd11/jobs/4912
=> Install build to fix metric-config-parser deploys

looker/definitions/ads.toml
Reverts mozilla/metric-hub#641
=> Revert "Update ads.toml - remove create_title and creative_url"

jetstream/outcomes/firefox_desktop/pin-email-and-calendar-tabs-early-day-user.toml, jetstream/outcomes/firefox_desktop/pin-email-and-calendar-tabs-existing-user.toml
Jetstream configs for [DS-3597](https://mozilla-hub.atlassian.net/browse/DS-3597)
=> add jetstream configs

jetstream/new-users-sidebar-genai.toml, jetstream/sidebar-vertical-tabs-layout-and-new-tools.toml
- [New users brief](https://docs.google.com/document/d/1tbP--diyXEdcWVqfShRH0Gr2IghnfIZGb0geVFm2X8M/edit?)
- [Existing users brief](https://docs.google.com/document/d/1r4cBAcm8Hh6VsIsqSaDk8bj56qoICnGOaRlOsRFKtHc/edit)
=> Sidebar new and existing users experiments

looker/definitions/ads.toml
Create new explore to track New Tab Ad Metrics and surface Mode reports within Looker
=> Add NewTab Ad Metrics to ads.toml

looker/definitions/ads.toml
* Fixing naming of ratio metrics
* Masking metrics from appearing as dimensions
=> Improving native ads reporting v2

definitions/fenix.toml, definitions/firefox_desktop.toml, definitions/firefox_ios.toml, definitions/focus_android.toml, definitions/focus_ios.toml, definitions/klar_android.toml, definitions/klar_ios.toml, lib/metric-config-parser/metric_config_parser/tests/data/definitions/firefox_desktop.toml
Explicitly set `columns_as_dimensions = true` for data sources that would otherwise get changed via https://github.com/mozilla/lookml-generator/pull/1144
=> Set columns_as_dimensions = true

opmon/firefox-ios-health.toml
Add tab loss detected metric to the iOS health dashboard
=> Add tab loss detected metric to the iOS health dashboard

jetstream/outcomes/firefox_desktop/pdf_handler.toml, jetstream/pdf-annotations-highlight-already-default-handler-v2.toml, jetstream/pdf-annotations-highlight-not-default-handler-v2.toml
@danielkberry - the dates in the experiment config are the same as what's in experimenter - will that still trigger a re-run?
=> add metric to pdf outcomes and rerun two experiments

definitions/fenix.toml, definitions/firefox_ios.toml
=> # feat(): deprecate old acquisition model references and update to use the current ones.

jetstream/recommend-bookmark-toolbar-existing-user.toml
added metrics after an experiment ended also testing ci-rerun-skip
=> [ci rerun-skip] Create recommend-bookmark-toolbar-existing-user.toml

jetstream/promote-add-ons-in-onboarding-release.toml
[copied from here](https://github.com/mozilla/metric-hub/commit/5d44640fd9a3a4b3ca25db5c540daafdac17b85c)
=> add addon metrics to promote-add-ons-in-onboarding-release.toml

jetstream/promote-add-ons-in-onboarding-release.toml
Reverts mozilla/metric-hub#786
=> [ci rerun-skip] Revert "add addon metrics to promote-add-ons-in-onboarding-release.toml"

jetstream/promote-add-ons-in-onboarding-release.toml
try 2 of [this](https://github.com/mozilla/metric-hub/pull/786)
=> add custom metrics for android addon experiment

jetstream/outcomes/firefox_desktop/relay.toml
Create a filtered version of the events data source for this outcome (and use it for the metrics).
=> feat: more efficient data source for relay outcome

definitions/firefox_desktop.toml, jetstream/outcomes/firefox_desktop/webcompat.toml
This is similar to Strict PBM, but has broken site reporter tool telemetry.
=> Add Webcompat JetStream Outcome

definitions/firefox_desktop.toml, looker/definitions/ads.toml
This PR adds client-level funnel metrics to looker.
Jira: https://mozilla-hub.atlassian.net/browse/AD-782
=> added ads funnel metrics

jetstream/encourage-use-of-search-bar-on-mobile.toml
the results for this experiment was hanging, @mikewilli suggested adding a filtered datasource to see if that helps.
=> add filtered data source for encourage-use-of-search-bar-on-mobile

jetstream/account-adoption-callout-passwords-early-day-relaunch.toml, jetstream/account-adoption-callout-passwords-existing-users-relaunch.toml
uploaded toml file to add the below custom metrics for Account adoption callout passwords experiment
FxA sign-rate
FxA configured
multi device signin
=> Account adoption callout passwords early day relaunch

looker/definitions/firefox_desktop.toml
- Fix CTR metrics
- Add widget and others engagement visits and clients
=> Hnt dashboard widget other reporting

jetstream/search-v1-homescreen.toml
Per experiment owner, this experiment can be ended and analysis skipped.
=> [ci rerun-skip] end search-v1-homescreen and skip analysis

definitions/firefox_desktop.toml
Add urlbar_impressions metric for search and suggest experiments.
=> adds a urlbar_impressions metric

definitions/firefox_desktop.toml
=> Move webcompat metrics to events_stream

jetstream/address-bar-update-launch-hold.toml
Hoping to see how May looks impact-wise.
=> Kicking off a manual update

jetstream/perplexity-secondary-search-initial.toml
adding toml with custom metrics and segments to the first perplexity experiment.
=> add perplexity-secondary-search-initial.toml

jetstream/accounts-vpn-promotion
=> Create accounts-vpn-promotion custom config

looker/definitions/ads.toml
Create ad counts metric to create revenue per ad metric/statistic for program health monitoring
=> create revenue per ad metric

jetstream/first-time-wallpaper-newtab.toml
overwrite majority of metrics with dummy expression and reference dummy table to attempt to get default stats without crash
=> [ci rerun-skip] Update first-time-wallpaper-newtab.toml

definitions/ads.toml
Adds a country join to ad-metrics-daily to get region
=> add countries join to ad-metrics-daily

definitions/ads.toml, looker/definitions/ads.toml
Ads the number of ad reports to looker
=> add number of reports to looker

looker/definitions/ads.toml, looker/definitions/firefox_desktop.toml
Fixes the ratio statistics by creating the num and denominator metrics needed for those missing them.
=> create metrics for ratio statistics

jetstream/perplexity-secondary-search-initial-part2.toml, jetstream/perplexity-secondary-search-initial.toml
to fix nimbus error preventing analysis rerun adding a profile group id to data source in both perplexity experiments
=> adding profile_group_id to perplexity

jetstream/pdf-annotations-signatures-ab-experiment.toml
need to add the defined segment to the segments list
=> fix pdf experiment segment

jetstream/intreaction-frecency-enhancement.toml
i missed no opping this any_sponsored_tiles_dismissals
=> [ci rerun-skip] Update intreaction-frecency-enhancement.toml

.github/workflows/validate-jetstream.yml, jetstream/1-click-pin-experiment.toml
Missed adding OIDC to the jetstream validate workflow
=> fix: add auth to jetstream validation workflow

jetstream/outcomes/firefox_desktop/incrementality_sponsored_tiles.toml
For future incrementality tile tests, we'll use this set of metrics that are relevant to the product.
=> create new outcome for tiles incrementality tests

jetstream/android-trending-and-recent-searches-v1.toml
added two outcomes to a previously run experiment
=> [ci rerun-skip] Create android-trending-and-recent-searches-v1.toml

jetstream/about-welcome-remove-import-screens.toml
missed adding "is_pinned" to the weekly and overall metrics
fixes #
=>  [ci rerun-skip] Update about-welcome-remove-import-screens.toml

jetstream/message-experiment-new-tab-mobile-qr-code.toml
custom config to downsample qr code experiment
fixes #
=>  [ci rerun-skip] Create message-experiment-new-tab-mobile-qr-code.toml

jetstream/offer-session-restore-on-by-default-to-new-users.toml
=> Add segmentation based on max concurrent tabs
